### PR TITLE
Consistently use pkg-config to find libssl and document the versions required.

### LINKED ISSUE #263: Unable to build xbps with OpenSSL 1.1
I'm attempting to build on Arch Linux and get several errors. I ran `make -k` in an attempt to log as many errors as possible. gcc is version 7.2.0. openssl is 1.1.0.g.

    fetch/common.c: In function ‘fetch_ssl_verify_altname’:
    fetch/common.c:898:3: error: ‘ASN1_STRING_data’ is deprecated [-Werror=deprecated-declarations]
       ns = (const char *)ASN1_STRING_data(name->d.ia5);
       ^~
    In file included from /usr/include/openssl/bn.h:31:0,
                     from /usr/include/openssl/asn1.h:24,
                     from /usr/include/openssl/objects.h:916,
                     from /usr/include/openssl/evp.h:27,
                     from /usr/include/openssl/x509.h:23,
                     from /usr/include/openssl/x509v3.h:14,
                     from fetch/common.c:62:
    /usr/include/openssl/asn1.h:553:1: note: declared here
     DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
     ^
    cc1: all warnings being treated as errors
    make[1]: *** [Makefile:62: fetch/common.o] Error 1
    pubkey2fp.c: In function ‘xbps_pubkey2fp’:
    pubkey2fp.c:68:13: error: storage size of ‘mdctx’ isn’t known
      EVP_MD_CTX mdctx;
                 ^~~~~
    pubkey2fp.c:94:27: error: dereferencing pointer to incomplete type ‘EVP_PKEY {aka struct evp_pkey_st}’
      if (EVP_PKEY_type(pPubKey->type) != EVP_PKEY_RSA) {
                               ^~
    In file included from /usr/include/openssl/asn1.h:24:0,
                     from /usr/include/openssl/objects.h:916,
                     from /usr/include/openssl/evp.h:27,
                     from pubkey2fp.c:16:
    pubkey2fp.c:107:26: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
      nLen = BN_num_bytes(pRsa->n);
                              ^
    pubkey2fp.c:143:2: error: implicit declaration of function ‘EVP_MD_CTX_cleanup’; did you mean ‘EVP_MD_CTX_create’? [-Werror=implicit-function-declaration]
      EVP_MD_CTX_cleanup(&mdctx);
      ^~~~~~~~~~~~~~~~~~
      EVP_MD_CTX_create
    pubkey2fp.c:143:2: error: nested extern declaration of ‘EVP_MD_CTX_cleanup’ [-Werror=nested-externs]
    pubkey2fp.c:68:13: error: unused variable ‘mdctx’ [-Werror=unused-variable]
      EVP_MD_CTX mdctx;
                 ^~~~~
    cc1: all warnings being treated as errors
    make[1]: *** [Makefile:72: pubkey2fp.o] Error 1
    make[1]: Target 'all' not remade because of errors.
    make: *** [Makefile:15: all] Error 1

### PR DESCRIPTION
**Pull request by eli-schwartz**
xbps is available in the Arch User Repository, but it doesn't build because it is incompatible with openssl 1.1

(It also doesn't build because of using -Werror in production code as part of "stable" releases instead of via CFLAGS on Travis, but that is another story.)

The standard way to fix this is to rely on pkg-config so that users can point PKG_CONFIG_PATH to their openssl-1.0 package or whatever, and fortunately that results in fewer lines of code that is also more robust. :smile:

Fixes #263, you can update the version requirements whenever xbps is updated to work with openssl 1.1

/cc @Vaelatern

### CODE REVIEW

File: configure [hunk 1]
```diff
@@ -675,43 +675,21 @@ else
...
-		echo "found version $($PKGCONFIG_BIN --modversion libssl)."
-		echo "CFLAGS += $($PKGCONFIG_BIN --cflags libssl)" >>$CONFIG_MK
-		echo "LDFLAGS +=        $($PKGCONFIG_BIN --libs libssl)" >>$CONFIG_MK
-		echo "STATIC_LIBS +=    $($PKGCONFIG_BIN --libs --static libssl)" \
-			>>$CONFIG_MK
-	fi
+printf "Checking for libssl via pkg-config ... "
+if $PKGCONFIG_BIN --exists 'libssl < 1.1' && ! $PKGCONFIG_BIN --exists libtls ; then
+	echo "found OpenSSL version $($PKGCONFIG_BIN --modversion libssl)."
+elif $PKGCONFIG_BIN --exists libssl libtls; then
```
Comment (Vaelatern) [inline configure]: This conditional can be wrong on systems with libtls from LibreSSL but also libssl from OpenSSL.

Comment (eli-schwartz) [reply configure]: Shoulda mentioned this yesterday on IRC. :grinning:
If so, I'm rather unsure how one would check in a suitably generic manner what type of libssl we have.

Are there indeed systems where this would be true for the default system libraries? How would this work anyway, as libtls.so seems to link to libcrypto.so and libssl.so?
I suppose in theory they can coexist with different soversions but in that case I would assume libssl.pc would come from libressl anyways. And I still feel like it would be the kind of thing that would set your computer on fire. :grinning:
(The likely argument for providing both, would be to try providing the shared libraries needed by proprietary binaries linked to libssl.so.1.0.0, but libressl provides those so I'm confused.)

I certainly wouldn't worry about PKG_CONFIG_PATH pointing to some isolated openssl-1.0 install where the system libssl is libressl, either.
